#!/bin/bash
# 
# Make a standalone emacs configuration.

if [ $# -ne 2 ]; then
    echo "`basename $0` <emacs.d-directory> <output file>" > /dev/null 1>&2
    exit 1
fi

if `which md5sum`; then
    MD5=md5sum
else
    MD5=md5
fi

EMACSD=$1
OUTPUT=$2

cd $EMACSD

UNIQUE=`find . \! -name '*.elc' -ls | $MD5`
UNIQUE=${UNIQUE:0:6}

shar `find . \! -name '*.elc' -print`           \
    | sed -e '1 i\
DIR=/tmp/emacs.$UNIQUE; if [ -d $DIR ] ; then emacs -q -l $DIR/init.el "$@"; exit; fi; echo "extracting emacs.d.."; OLDDIR=$PWD; mkdir -p $DIR; cd $DIR'          \
    | sed -e "1 i\\
UNIQUE=$UNIQUE"                                 \
    | sed -e '1 i\
#!/bin/sh' \
    | sed -e '/^exit/,$ d'                      \
    | sed -e '$ a\
cd $OLDDIR; emacs -q -l $DIR/init.el "$@"'      \
    | sed -e 's/^echo . .*//'                   \
    > $OUTPUT

chmod 0744 $OUTPUT
